/*
 This package contains generated object models for webservice types.
 Generated by Axis2
 */

@javax.xml.bind.annotation.XmlSchema(namespace = "http://developer.intuit.com/",
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED) package com.intuit.developer;


